version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3

jobs:

  publish:
    parameters:
      imageTag:
        type: string
    machine:
      image: ubuntu-2204:2022.04.1
      docker_layer_caching: true
    environment:
      ECR_REPO: 427052161823.dkr.ecr.us-east-1.amazonaws.com/contentful/data/redash-redshift
    steps:
      - checkout
      - run:
          name: ECR Login
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 427052161823.dkr.ecr.us-east-1.amazonaws.com
      - run:
          name: Build image
          command: |
            docker build -t $ECR_REPO:$CIRCLE_SHA1 .
            docker tag $ECR_REPO:$CIRCLE_SHA1 $ECR_REPO:<< parameters.imageTag >>
      - run:
          name: Publish image
          command: |
            docker push $ECR_REPO:$CIRCLE_SHA1
            docker push $ECR_REPO:<< parameters.imageTag >>

workflows:
  test-build-and-deploy:
    jobs:
      - publish:
          name: publishStaging
          imageTag: staging
      - publish:
          name: publishProduction
          imageTag: production
          filters:
            branches:
              only: main
